# Generated by Django 4.1.3 on 2025-10-20 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StringAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.TextField(unique=True)),
                ("length", models.IntegerField()),
                ("is_palindrome", models.BooleanField()),
                ("word_count", models.IntegerField()),
                ("unique_char_count", models.IntegerField()),
                ("character_frequency", models.JSONField()),
                ("sha256_hash", models.CharField(max_length=64, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "String Analyses",
            },
        ),
    ]
